eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
   
    
microservices:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/savePayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
        


      
